#pragma once

#include "domain/Bookmark.hpp"
#include "domain/ChapterInfo.hpp"
#include "domain/MediaItem.hpp"
#include "domain/PlaybackEndReason.hpp"
#include "domain/PlaybackDiagnostics.hpp"
#include "domain/PlayerProfile.hpp"
#include "domain/TrackInfo.hpp"
#include "infrastructure/storage/SqliteStore.hpp"
#include "services/media/MetadataScanService.hpp"
#include "ui/ShortcutBinding.hpp"

#include <QByteArray>
#include <QElapsedTimer>
#include <QHash>
#include <QJsonObject>
#include <QMainWindow>
#include <QSet>
#include <QSize>

class QAction;
class QActionGroup;
class QCheckBox;
class QComboBox;
class QDragEnterEvent;
class QDockWidget;
class QCloseEvent;
class QDoubleSpinBox;
class QEvent;
class QGridLayout;
class QHBoxLayout;
class QImage;
class QLabel;
class QListWidget;
class QListWidgetItem;
class QListView;
class QLineEdit;
class QModelIndex;
class QMenu;
class QDropEvent;
class QPoint;
class QProgressBar;
class QProcess;
class QPropertyAnimation;
class QPushButton;
class QRect;
class QScrollArea;
class QSlider;
class QSortFilterProxyModel;
class QStyledItemDelegate;
class QSpinBox;
class QString;
class QShowEvent;
class QTabBar;
class QTabWidget;
class QTimer;
class QToolButton;
class QTreeWidget;
class QTreeWidgetItem;

namespace revaplayer::application {
class BookmarkController;
class HistoryController;
class PlaybackController;
class PlaylistController;
class SettingsController;
class SnapshotController;
}

namespace revaplayer::infrastructure::mpv {
class MpvRenderHost;
}

namespace revaplayer::infrastructure::storage {
struct PlaybackHistoryRecord;
}

namespace revaplayer::services::media {
class ThumbnailService;
}

namespace revaplayer::ui {

class ControlBar;
class BookmarkDialog;
class HoverPreviewPopup;
class MediaInfoDialog;
class SettingsDialog;
class MediaInformationOverlay;
class VideoViewport;

class MainWindow final : public QMainWindow {
    Q_OBJECT

public:
    MainWindow(revaplayer::application::BookmarkController *bookmarkController,
               revaplayer::application::HistoryController *historyController,
               revaplayer::application::PlaybackController *playbackController,
               revaplayer::application::PlaylistController *playlistController,
               revaplayer::application::SnapshotController *snapshotController,
               revaplayer::application::SettingsController *settingsController,
               QWidget *parent = nullptr);
    ~MainWindow() override = default;

    [[nodiscard]] revaplayer::infrastructure::mpv::MpvRenderHost *renderHost() const;
    void openStartupRequest(const QString &startupUrl, const QStringList &startupFiles);

protected:
    void closeEvent(QCloseEvent *event) override;
    void changeEvent(QEvent *event) override;
    void dragEnterEvent(QDragEnterEvent *event) override;
    void dropEvent(QDropEvent *event) override;
    bool eventFilter(QObject *watched, QEvent *event) override;
    void keyPressEvent(QKeyEvent *event) override;
    void showEvent(QShowEvent *event) override;

private slots:
    void openFiles();
    void openFolder();
    void openUrl();
    void loadSubtitleFile();
    void showMediaInfoDialog();
    void takeScreenshot();
    void addBookmark();
    void onBookmarkActivated(QListWidgetItem *item);
    void showBookmarksContextMenu(const QPoint &position);
    void resetWindowLayout();
    void saveCurrentLayoutPreset();
    void loadLayoutPreset();
    void deleteLayoutPreset();
    void showSettingsDialog();
    void showViewportContextMenu(const QPoint &position);
    void showPlaylistContextMenu(const QPoint &position);
    void onLoadStarted(const QString &displayTarget);
    void onIdleChanged(bool idleActive);
    void applyIdleStateReset();
    void onPlaylistActivated(const QModelIndex &index);
    void onChapterActivated(QListWidgetItem *item);
    void onTrackActivated(QTreeWidgetItem *item, int column);
    void onPlaybackPositionChanged(double positionSeconds, double durationSeconds);
    void onPausedChanged(bool paused);
    void onVolumeChanged(int volume);
    void onMutedChanged(bool muted);
    void onTitleChanged(const QString &title);
    void onFileLoaded();
    void onFileEnded(revaplayer::domain::PlaybackEndReason reason, const QString &message);
    void onPreviewRequested(double timeSeconds, const QPoint &globalAnchor);
    void onPreviewHidden();
    void onThumbnailReady(const QString &source, qint64 bucketMilliseconds, const QImage &image);
    void onThumbnailUnavailable(const QString &source, qint64 bucketMilliseconds, const QString &reason);
    void onMediaMetadataReady(const revaplayer::services::media::MediaScanResult &result);
    void onMediaMetadataUnavailable(const QString &source, const QString &reason);
    void onPlaylistChanged(const QVector<revaplayer::domain::PlaylistEntry> &entries, int currentIndex);
    void onChaptersChanged(const QVector<revaplayer::domain::ChapterInfo> &chapters, int currentIndex);
    void onTracksChanged(const QVector<revaplayer::domain::TrackInfo> &tracks);
    void showError(const QString &message);

private:
    enum class SidePanel {
        Playlist,
        Details,
    };

    void setupUi();
    void setupMenuBar();
    void setupDockWidgets();
    void setupPlaybackActions();
    void connectUi();
    void applyUiPreferences();
    void updateStatusBarVisibility();
    void applyShortcutPreferences();
    [[nodiscard]] bool triggerConfiguredShortcut(const QKeyEvent *event);
    void applyPlaybackProfile(bool announce = false);
    void applyRuntimePreferences();
    void updateVideoPointerAutoHide();
    void updateDisplaySleepInhibition();
    void applySubtitlePreviewState(bool visible,
                                   double scale,
                                   int position,
                                   const QString &fontFamily,
                                   int fontSize,
                                   const QString &assOverride,
                                   bool updateCurrentState = false);
    void syncVideoActionStates();
    void syncSubtitleActionStates();
    void showMediaInformationOverlay();
    void hideMediaInformationOverlay();
    void updateMediaInformationOverlay();
    void updateMediaInfoDialog(bool force = false);
    void requestPendingThumbnailPreview();
    [[nodiscard]] bool ensureBookmarkStorageReady(bool announceFailure = false);
    void beginLoadFeedback(const QString &displayTarget);
    void finalizeActiveMediaLoadFromBackend();
    void persistPlaybackProgress(bool completed, bool force = false);
    void maybeResumePlayback();
    [[nodiscard]] bool clearStoredProgressForSource(const QString &source);
    [[nodiscard]] int clearStoredProgressForSources(const QStringList &sources);
    [[nodiscard]] QStringList currentPlaylistProgressSources() const;
    void refreshProgressDisplaysAfterReset();
    void resetSelectedPlaylistItemProgress(const QModelIndex &index);
    void markSelectedPlaylistItemCompleted(const QModelIndex &index);
    void resetCurrentPlaylistProgress();
    void showIdleOverlay(const QString &message);
    void updatePanelPresentationMode();
    void applyStartupSidePanelVisibility();
    void loadOverlayPanelWidthsFromSettings();
    void setSidePanelVisible(SidePanel panel, bool visible, bool raise = true);
    void toggleSidePanel(SidePanel panel);
    [[nodiscard]] bool isSidePanelVisible(SidePanel panel) const;
    [[nodiscard]] bool panelsOverlayEnabled() const;
    [[nodiscard]] QDockWidget *sidePanelDock(SidePanel panel) const;
    [[nodiscard]] int overlayPanelWidthFor(SidePanel panel) const;
    void setOverlayPanelWidthFor(SidePanel panel, int width, bool persist = true);
    void syncOverlayPanelWidthForActivePanel();
    void syncPanelToggleActions();
    void toggleFullscreen();
    void updateFullscreenChromeMode();
    void setFullscreenChromeVisible(bool topVisible, bool bottomVisible);
    void handleFullscreenPointerActivity(const QPoint &localPosition);
    void handleViewportPointerLeave();
    void scheduleManagedPointerLeaveCheck(int delayMs = -1);
    void evaluateManagedPointerLeave();
    void scheduleFullscreenChromeHide(int delayMs = 1400);
    void updateControlBarPresentationMode();
    void updateVideoOverlayGeometry();
    [[nodiscard]] QRect overlaySidePanelGeometry() const;
    [[nodiscard]] QRect hiddenOverlaySidePanelGeometry(const QRect &targetGeometry) const;
    void animateOverlayDock(QDockWidget *dock, bool visible, bool raisePanel);
    [[nodiscard]] bool pointerInsideManagedChrome(const QPoint &globalPosition) const;
    void focusCurrentPlaylistItem(bool ensureVisible = true);
    void refreshPlaylistSummary();
    void refreshPlaylistInspector();
    void refreshPlaylistViewLayout();
    void updatePlaylistChromeState();
    void clearPendingPlaylistSelection();
    void clearPendingCurrentMediaRestore();
    void armPendingCurrentMediaRestore(const QString &source, double positionSeconds);
    bool applyPendingCurrentMediaRestore();
    [[nodiscard]] QString playlistSourceForIndex(int playlistIndex) const;
    bool preparePlaylistNavigationToIndex(int playlistIndex);
    void selectPlaylistIndexWithResumeGuard(int playlistIndex);
    void navigatePlaylistWithResumeGuard(bool forward);
    void capturePanelStateForPlaylistActivation();
    void restorePanelStateAfterPlaylistActivation(bool clearPending = false);
    void hidePlaylistPanelImmediately();
    void enforceHiddenSidePanelsAfterMediaOpen(int suppressionMs = 900, bool scheduleFollowUp = true);
    [[nodiscard]] int resolvePendingPlaylistSelectionIndex(
        const QVector<revaplayer::domain::PlaylistEntry> &entries) const;
    void schedulePendingPlaylistSelectionRetry(int delayMs = 0);
    void attemptPendingPlaylistSelection();
    void restorePendingPlaylistOrderIfReady();
    void clearPendingPlaylistViewportRestore();
    void restorePendingPlaylistViewport(bool clearPending = true);
    [[nodiscard]] QStringList selectedPlaylistSources() const;
    void restorePlaylistSelectionFromSources(const QStringList &sources, const QString &currentSource);
    void applyRequestedPlaylistOrder(const QVector<int> &orderedIndices);
    void applyPlaylistPanelDisplayPreferences();
    void rebuildDetailsTabStrip();
    void syncDetailsTabStripState();
    void scrollDetailsTabButtonIntoView(int index);
    void scrollPinnedCourseTabIntoView(int index);
    void showPinnedCourseContextMenu(const QPoint &position);
    void editPinnedCourseByPath(const QString &folderPath);
    void removePinnedCourseByPath(const QString &folderPath);
    void previewPinnedCourseTab(int index);
    void browseFolderPath(const QString &folderPath, bool resetHistory = false);
    void browseBackFolder();
    void exitPinnedCourseBrowserMode();
    void applyVisiblePlaylistEntries();
    void schedulePlaylistMetadataRefresh(int delayMs = 0);
    [[nodiscard]] QSet<QString> playlistMetadataAutoScanTargets() const;
    void resetPlaylistMetadataScanState(bool cancelActiveScan);
    void updatePlaylistMetadataScanButtonState();
    int enqueuePlaylistMetadataScan(bool forceRescan = false);
    void warmPlaylistThumbnail(const QString &source, double durationSeconds = 0.0);
    void requestPlaylistThumbnailBatch(bool includeInitialRows = true);
    void enqueuePlaylistThumbnail(const QString &source, double durationSeconds);
    void startNextPlaylistThumbnailRequest();
    void handlePlaylistThumbnailProcessFinished(int exitCode, bool normalExit);
    void clearPlaylistThumbnailQueue(bool cancelActiveRequest);
    void applySelectedTheme(bool announce = false);
    void setRepeatMode(const QString &mode, bool announce = true);
    void syncRepeatModeActions();
    void setAlwaysOnTopEnabled(bool enabled, bool announce = true);
    void updateActionStates();
    void updatePlaylistReorderAvailability();
    void applyControlBarPreferences();
    void updateControlBarBufferedState();
    void restorePersistentState();
    void persistWindowState();
    void updateWindowTitle();
    [[nodiscard]] QString effectiveCurrentMediaTitle() const;
    void reloadCurrentFolderPlaylist();
    [[nodiscard]] QStringList resolvedOpenFiles(const QStringList &requestedFiles,
                                                bool *expandedFromFolder = nullptr) const;
    [[nodiscard]] QStringList siblingMediaPlaylist(const QString &selectedFilePath) const;
    void seekBySecondsWithFeedback(int seconds);
    void adjustVolumeWithFeedback(int delta);
    void showActionResult(const QString &statusMessage,
                          const QString &overlayMessage = QString {},
                          int timeoutMs = 3000);
    void showPlaybackFeedback(const QString &message);
    void showPlaybackSpeedFeedback(double speed, bool reset = false);
    void showVolumeFeedback(int volume);
    void applyVideoViewportTransform();
    void setVideoZoomFactor(double factor, bool showFeedback = true);
    void adjustVideoZoomFactor(double delta);
    void resetVideoZoomAndPan(bool showFeedback = true);
    void setVideoAlignment(double horizontal, double vertical, bool showFeedback = true);
    void adjustVideoAlignment(double deltaX, double deltaY, bool showFeedback = true);
    void handleVideoPanDelta(const QPoint &deltaPixels);
    [[nodiscard]] double videoZoomStepSetting() const;
    [[nodiscard]] double videoMinimumZoomSetting() const;
    [[nodiscard]] double videoMaximumZoomSetting() const;
    [[nodiscard]] QString videoZoomDefaultBehaviorSetting() const;
    [[nodiscard]] bool videoZoomResetOnFileChangeEnabled() const;
    [[nodiscard]] QString videoZoomRememberModeSetting() const;
    [[nodiscard]] double videoPanSensitivitySetting() const;
    [[nodiscard]] bool videoZoomConstrainPanningEnabled() const;
    [[nodiscard]] QString videoZoomWheelBehaviorSetting() const;
    [[nodiscard]] QString videoZoomFullscreenBehaviorSetting() const;
    void applyConfiguredZoomStateForCurrentMedia();
    void rememberVideoZoomStateForCurrentMedia();
    [[nodiscard]] bool applyRememberedVideoZoomStateForSource(const QString &source);
    [[nodiscard]] QJsonObject currentVideoTransformState() const;
    void applyAdvancedSubtitlePreferences();
    [[nodiscard]] bool rememberSubtitleTrackChoiceEnabled() const;
    void applyRememberedSubtitleTrackChoice(const QVector<revaplayer::domain::TrackInfo> &tracks);
    void rememberSelectedSubtitleTrackChoice(const QVector<revaplayer::domain::TrackInfo> &tracks);
    [[nodiscard]] QVector<revaplayer::ui::ShortcutBinding> buildShortcutBindings() const;
    [[nodiscard]] QAction *actionForShortcutId(const QString &shortcutId) const;
    void reloadBookmarks();
    void removeSelectedBookmark();
    void populateBookmarks(const QVector<revaplayer::domain::Bookmark> &bookmarks);
    void filterBookmarks();
    void refreshBookmarkFilters();
    void importBookmarksForCurrentMedia();
    void exportBookmarksForCurrentMedia() const;
    void populateChapters(const QVector<revaplayer::domain::ChapterInfo> &chapters, int currentIndex);
    void populateTracks(const QVector<revaplayer::domain::TrackInfo> &tracks);
    void rebuildVideoQualityMenu(const QVector<revaplayer::domain::TrackInfo> &tracks);
    void rebuildControlBarSubtitleMenu(const QVector<revaplayer::domain::TrackInfo> &tracks);
    bool openMediaSource(const QString &input);
    bool openLocalMediaFiles(const QStringList &requestedFiles, bool revealPlaylistPanel = true);
    void showSpecialSourceDialog(const QString &title, const QString &placeholderText, const QString &hintText);
    void showQuickHelpDialog();
    void showAboutDialog();
    void clearApplicationCache();
    void factoryResetApplication();
    void clearHistoryPanel();
    void reloadHistoryPanel();
    void populateHistory(const QVector<revaplayer::infrastructure::storage::PlaybackHistoryRecord> &entries);
    void rebuildHistoryLookupCache();
    void filterHistoryPanel();
    void reloadFavoritesPanel();
    void filterFavoritesPanel();
    void addFavoriteFile();
    void openSelectedFavorite();
    void removeSelectedFavorite();
    bool addMediaSourceToFavorites(const QString &source,
                                   const QString &title,
                                   const QString &addedMessage,
                                   const QString &alreadyFavoriteMessage);
    void updateFavoriteThumbnailForSource(const QString &source, const QImage &image);
    void clearSceneBrowser(const QString &message = QString {});
    void rebuildSceneBrowser(bool force = false);
    void refreshSceneBrowserPrompt(bool preserveGeneratedScenes = true);
    void filterSceneBrowser();
    void exportSceneImages();
    void bookmarkSelectedScene();
    void requestNextSceneThumbnail();
    void populateSecondarySubtitleOptions();
    void applySecondarySubtitleSelection();
    void setSubtitleDelayWithFeedback(double delaySeconds, bool resetRequested = false);
    void saveRememberedSubtitleDelayForCurrentMedia();
    void removeRememberedSubtitleDelayForCurrentMedia();
    void applyRememberedSubtitleDelayForCurrentMedia();
    void adjustSubtitleDelayWithFeedback(double deltaSeconds);
    void resetSubtitleDelayWithFeedback();
    void showManualSubtitleDelayDialog();
    void setAudioDelayWithFeedback(double delaySeconds, bool resetRequested = false);
    void showManualAudioDelayDialog();
    void maybeAutoLoadMatchingLocalSubtitles();
    [[nodiscard]] QString subtitleAutoLoadModeSetting() const;
    [[nodiscard]] QSet<QString> subtitleAutoLoadExtensionsSetting() const;
    void applySmartSubtitleSelection(bool allowLocalSubtitleLoad = true, bool announce = false);
    void triggerSubtitleDownload();
    void applyAudioFilterState();
    void applyVideoFilterState();
    void dispatchWheelAction(int steps, Qt::KeyboardModifiers modifiers);
    void dispatchClickAction(Qt::MouseButton button);
    void dispatchMouseSideButtonAction(bool forward);
    void dispatchDoubleClickAction(Qt::MouseButton button);
    void dispatchMiddleClickAction();
    [[nodiscard]] QVector<int> selectedPlaylistIndices() const;
    void removeSelectedPlaylistItems();
    void keepOnlySelectedPlaylistItems();
    void removeDuplicatePlaylistItems();
    void openPlaylistSources(const QStringList &sources,
                             int selectedIndex = 0,
                             bool revealPlaylistPanel = true,
                             bool exitFolderBrowserMode = true);
    void saveCurrentPlaylistSnapshot();
    void loadPlaylistSnapshot(const QString &snapshotKey);
    void deletePlaylistSnapshot(const QString &snapshotKey);
    [[nodiscard]] QStringList playlistSnapshotKeys() const;
    [[nodiscard]] QString playlistSnapshotLabel(const QString &snapshotKey) const;
    void buildSmartPlaylistFromSameFolder();
    void buildSmartPlaylistFromSameExtension();
    void buildSmartPlaylistFromIncompleteHistory();
    void buildSmartPlaylistFromRecentHistory();
    void buildSmartPlaylistFromNoSubtitles();
    void buildSmartPlaylistFromFavorites();
    void loadSmartPlaylistRule(const QString &ruleKey);
    void saveSmartPlaylistRule(const QString &ruleKind, const QString &defaultName = {});
    void deleteSmartPlaylistRule(const QString &ruleKey);
    void toggleFavoriteCurrentMedia();
    void pinCurrentMediaFolder();
    void openPinnedCourseTab(int index);
    void managePinnedCourses();
    void showPlaylistPanelSettingsDialog();
    void showDetailsPanelSettingsDialog();
    void saveCurrentPlaylistView();
    void editCurrentPlaylistView();
    void applyPlaylistViewPreset(const QString &presetKey, bool announce = false);
    void editSelectedPlaylistItemMetadata();
    void exportBookmarksAsQuizCsv();
    void updateAdaptiveUiLayout();
    void updateBookmarkSelectionPreview();
    void requestNextBookmarkThumbnail();
    void refreshFavoritesViewLayout();
    void normalizeWindowGeometryAfterRestore();
    void clearRuntimeCaches();
    bool clearDiskCaches(QString *errorMessage = nullptr);
    void dispatchGestureAction(const QString &directionId);
    void openCompareSource();
    void setCompareMode(const QString &modeId);
    void toggleCompareView();
    void showScreenshotSuiteDialog();
    void performBurstScreenshotStep();
    [[nodiscard]] QStringList preferredSubtitleLanguages() const;
    [[nodiscard]] QString currentContentTypeId() const;
    [[nodiscard]] QJsonObject captureMediaProfileState() const;
    void applyMediaProfileState(const QJsonObject &state, bool announce = false);
    void saveMediaProfileForFile();
    void saveMediaProfileForType();
    void clearMediaProfileForFile();
    void clearMediaProfileForType();
    void applyStoredMediaProfiles();
    [[nodiscard]] bool historyEnabled() const;
    [[nodiscard]] bool clearHistoryOnExitEnabled() const;
    [[nodiscard]] bool resumeEnabled() const;
    [[nodiscard]] int shortSeekStepSeconds() const;
    [[nodiscard]] int longSeekStepSeconds() const;
    [[nodiscard]] int volumeStep() const;
    [[nodiscard]] bool mouseWheelVolumeEnabled() const;
    [[nodiscard]] int mouseWheelVolumeStep() const;
    [[nodiscard]] QString mouseWheelActionId() const;
    [[nodiscard]] int mouseWheelSeekStepSeconds() const;
    [[nodiscard]] bool mouseNavigationSeekEnabled() const;
    [[nodiscard]] int mouseNavigationSeekStepSeconds() const;
    [[nodiscard]] QString mouseSideButtonsActionId() const;
    [[nodiscard]] QString clickActionId() const;
    [[nodiscard]] QString doubleClickActionId() const;
    [[nodiscard]] QString middleClickActionId() const;
    [[nodiscard]] bool actionFeedbackOverlayEnabled() const;
    [[nodiscard]] bool expressiveControlLabelsEnabled() const;
    [[nodiscard]] bool fullscreenAutoHideEnabled() const;
    [[nodiscard]] int fullscreenRevealMargin() const;
    [[nodiscard]] bool fullscreenEdgePanelRevealEnabled() const;
    [[nodiscard]] bool fullscreenSideSelectorEnabled() const;
    [[nodiscard]] bool windowedEdgePanelRevealEnabled() const;
    [[nodiscard]] QString defaultSidePanelId() const;
    [[nodiscard]] bool doubleClickFullscreenEnabled() const;
    [[nodiscard]] QString pointerRightEdgeActionId(bool fullscreenContext) const;
    [[nodiscard]] QString pointerRightEdgeLeaveActionId() const;
    [[nodiscard]] int pointerRightEdgeMargin() const;
    [[nodiscard]] int pointerLeaveDelayMs() const;
    [[nodiscard]] bool pointerKeepControlsVisibleWhilePanelOpen() const;
    [[nodiscard]] QString mouseZoneActionId(const QString &zoneId) const;
    void applyMouseZoneAction(const QString &zoneId);
    void applyConfiguredRightEdgeAction(const QString &actionId);
    void applyConfiguredRightEdgeLeaveAction(const QString &actionId);
    [[nodiscard]] int thumbnailPopupWidth() const;
    [[nodiscard]] int thumbnailPopupVerticalOffset() const;
    [[nodiscard]] int thumbnailPopupScreenPadding() const;
    [[nodiscard]] int historyLimit() const;
    [[nodiscard]] bool autoLoadSiblingMediaEnabled() const;
    [[nodiscard]] bool showPlaylistPanelOnFolderLoad() const;
    [[nodiscard]] bool naturalSortFolderPlaylistEnabled() const;
    [[nodiscard]] bool playlistShowFullPathsEnabled() const;
    [[nodiscard]] bool playlistShowIndexPrefixesEnabled() const;
    [[nodiscard]] bool playlistAutoFollowEnabled() const;
    [[nodiscard]] bool rotateFolderPlaylistToCurrentEnabled() const;
    [[nodiscard]] QString selectedThemeId() const;
    [[nodiscard]] QString startupWindowMode() const;
    [[nodiscard]] QString startupCanvasStyleId() const;
    [[nodiscard]] QString configuredRepeatMode() const;
    [[nodiscard]] double configuredStartupPlaybackSpeed() const;
    [[nodiscard]] bool sessionWidePlaybackSpeedEnabled() const;
    [[nodiscard]] bool subtitleAutoSelectEnabled() const;
    [[nodiscard]] bool subtitlePreferExternal() const;
    [[nodiscard]] bool subtitleAutoLoadLocalMatchesEnabled() const;
    [[nodiscard]] double subtitleSyncSmallStep() const;
    [[nodiscard]] QString subtitleDownloadCommandTemplate() const;
    [[nodiscard]] int sceneBrowserStepSeconds() const;
    [[nodiscard]] int sceneBrowserMaxItems() const;
    void updateSidePanelSelectorState();
    void trimHistoryToLimit();
    void refreshPlaylistPresentationData();
    void clearFileSystemCache();
    void refreshPlaylistPlaybackProgress();
    void refreshPlaylistProgressIndicators();
    void acquireDisplaySleepInhibition();
    void releaseDisplaySleepInhibition();
    bool startSystemdDisplayInhibitor();
    void stopSystemdDisplayInhibitor();
    void rebuildPinnedCourseTabs(bool includeProgress = true);
    void rebuildPlaylistViewTabs();
    void reloadHomeDashboard(bool includeSavedListProgress = true);
    void applyStartupCanvasAppearance();
    void applyCustomPlaylistThemeColors();
    void updateHomeDashboardSectionLayout();
    void updateHomeDashboardVisibility();
    void showFirstRunWizardIfNeeded();
    [[nodiscard]] QJsonObject captureLayoutPresetState() const;
    [[nodiscard]] bool applyLayoutPresetState(const QJsonObject &state, QString *errorMessage = nullptr);
    [[nodiscard]] QString uiDensityId() const;
    [[nodiscard]] QString uiAccentId() const;
    [[nodiscard]] QString uiModeId() const;
    [[nodiscard]] bool dashboardEnabled() const;
    [[nodiscard]] bool dashboardShowWhenIdle() const;
    [[nodiscard]] bool dashboardSectionEnabled(const char *settingKey) const;
    [[nodiscard]] bool progressTrackingModeEnabled() const;
    [[nodiscard]] int progressCompletionThreshold() const;
    [[nodiscard]] bool progressBadgesEnabled() const;
    [[nodiscard]] QString playlistViewModeId() const;
    [[nodiscard]] QString playlistViewDensityId() const;
    [[nodiscard]] QString playlistLayoutFitId() const;
    [[nodiscard]] QString playlistCardZoomId() const;
    [[nodiscard]] QString playlistThumbnailShapeId() const;
    [[nodiscard]] QStringList playlistVisibleColumns() const;
    [[nodiscard]] QStringList playlistVisibleDetailsTabIds() const;
    [[nodiscard]] QString playlistPreferredDetailsTabId() const;
    [[nodiscard]] QString playlistSortModeId() const;
    [[nodiscard]] bool adaptiveUiEnabled() const;
    [[nodiscard]] int adaptiveUiBreakpoint() const;
    [[nodiscard]] int uiRadiusPx() const;
    [[nodiscard]] int uiSpacingPx() const;
    [[nodiscard]] int uiFontScalePercent() const;
    [[nodiscard]] int uiFontWeightValue() const;
    [[nodiscard]] double uiLetterSpacingValue() const;
    [[nodiscard]] int uiBorderContrastPercent() const;
    [[nodiscard]] int uiShadowStrengthPercent() const;
    [[nodiscard]] int uiBlurStrengthPercent() const;
    [[nodiscard]] int uiAnimationSpeedPercent() const;
    [[nodiscard]] QString uiAnimationEasingId() const;
    [[nodiscard]] int uiOverlayOpacityPercent() const;

    revaplayer::application::BookmarkController *bookmarkController_ {nullptr};
    revaplayer::application::HistoryController *historyController_ {nullptr};
    revaplayer::application::PlaybackController *playbackController_ {nullptr};
    revaplayer::application::PlaylistController *playlistController_ {nullptr};
    revaplayer::application::SnapshotController *snapshotController_ {nullptr};
    revaplayer::application::SettingsController *settingsController_ {nullptr};
    revaplayer::application::PlaybackController *comparePlaybackController_ {nullptr};
    revaplayer::services::media::ThumbnailService *thumbnailService_ {nullptr};
    revaplayer::services::media::MetadataScanService *metadataScanService_ {nullptr};
    QWidget *videoViewportRow_ {nullptr};
    VideoViewport *videoViewport_ {nullptr};
    VideoViewport *compareVideoViewport_ {nullptr};
    ControlBar *controlBar_ {nullptr};
    HoverPreviewPopup *hoverPreviewPopup_ {nullptr};
    MediaInformationOverlay *mediaInformationOverlay_ {nullptr};
    MediaInfoDialog *mediaInfoDialog_ {nullptr};
    QTimer *previewRequestTimer_ {nullptr};
    QTimer *previewStatusTimer_ {nullptr};
    QTimer *metadataRefreshTimer_ {nullptr};
    QTimer *pendingPlaylistSelectionTimer_ {nullptr};
    QTimer *mediaInformationOverlayTimer_ {nullptr};
    QTimer *fullscreenChromeTimer_ {nullptr};
    QTimer *pointerLeaveTimer_ {nullptr};
    QWidget *fullscreenTopBar_ {nullptr};
    QLabel *fullscreenTitleLabel_ {nullptr};
    QToolButton *fullscreenOpenButton_ {nullptr};
    QToolButton *fullscreenPlaylistButton_ {nullptr};
    QToolButton *fullscreenDetailsButton_ {nullptr};
    QToolButton *fullscreenPreferencesButton_ {nullptr};
    QToolButton *fullscreenExitFullscreenButton_ {nullptr};
    QWidget *sidePanelSelector_ {nullptr};
    QToolButton *sidePanelPlaylistButton_ {nullptr};
    QToolButton *sidePanelDetailsButton_ {nullptr};
    QDockWidget *playlistDock_ {nullptr};
    QWidget *playlistResizeHandle_ {nullptr};
    QPropertyAnimation *playlistDockAnimation_ {nullptr};
    QWidget *playlistHeaderBar_ {nullptr};
    QWidget *playlistCoursesRow_ {nullptr};
    QWidget *playlistViewsRow_ {nullptr};
    QScrollArea *pinnedCoursesScrollArea_ {nullptr};
    QTabBar *pinnedCoursesTabBar_ {nullptr};
    QTabBar *playlistViewPresetsTabBar_ {nullptr};
    QListView *playlistView_ {nullptr};
    QStyledItemDelegate *playlistDelegate_ {nullptr};
    QSortFilterProxyModel *playlistFilterModel_ {nullptr};
    QLineEdit *playlistSearchEdit_ {nullptr};
    QLabel *playlistSummaryLabel_ {nullptr};
    QWidget *playlistProgressRow_ {nullptr};
    QLabel *playlistProgressTextLabel_ {nullptr};
    QLabel *playlistTotalDurationLabel_ {nullptr};
    QProgressBar *playlistAggregateProgressBar_ {nullptr};
    QToolButton *playlistRefreshButton_ {nullptr};
    QToolButton *playlistAutoFolderButton_ {nullptr};
    QToolButton *playlistAutoFollowButton_ {nullptr};
    QToolButton *playlistPanelSettingsButton_ {nullptr};
    QToolButton *playlistPinCourseButton_ {nullptr};
    QToolButton *playlistManageCoursesButton_ {nullptr};
    QToolButton *playlistSaveViewButton_ {nullptr};
    QToolButton *playlistEditViewButton_ {nullptr};
    QDockWidget *detailsDock_ {nullptr};
    QWidget *detailsResizeHandle_ {nullptr};
    QPropertyAnimation *detailsDockAnimation_ {nullptr};
    QScrollArea *detailsTabsStripScrollArea_ {nullptr};
    QWidget *detailsTabsStripContainer_ {nullptr};
    QHBoxLayout *detailsTabsStripLayout_ {nullptr};
    QVector<QPushButton *> detailsTabButtons_;
    QTabWidget *detailsTabs_ {nullptr};
    QToolButton *detailsPanelSettingsButton_ {nullptr};
    QToolButton *detailsSwitchPanelButton_ {nullptr};
    QLineEdit *historySearchEdit_ {nullptr};
    QLabel *historySummaryLabel_ {nullptr};
    QToolButton *historyRefreshButton_ {nullptr};
    QToolButton *historyClearButton_ {nullptr};
    QListWidget *historyList_ {nullptr};
    QWidget *favoritesPage_ {nullptr};
    QLineEdit *favoritesSearchEdit_ {nullptr};
    QToolButton *favoritesRefreshButton_ {nullptr};
    QToolButton *favoritesAddButton_ {nullptr};
    QToolButton *favoritesOpenButton_ {nullptr};
    QToolButton *favoritesOpenAllButton_ {nullptr};
    QToolButton *favoritesCurrentButton_ {nullptr};
    QToolButton *favoritesRemoveButton_ {nullptr};
    QWidget *bookmarksPage_ {nullptr};
    QLineEdit *bookmarkSearchEdit_ {nullptr};
    QComboBox *bookmarkCategoryComboBox_ {nullptr};
    QToolButton *bookmarkAddButton_ {nullptr};
    QToolButton *bookmarkImportButton_ {nullptr};
    QToolButton *bookmarkExportButton_ {nullptr};
    QToolButton *bookmarkDeleteButton_ {nullptr};
    QToolButton *bookmarkQuizCsvButton_ {nullptr};
    QLabel *bookmarkPreviewImageLabel_ {nullptr};
    QLabel *bookmarkPreviewTitleLabel_ {nullptr};
    QLabel *bookmarkPreviewNoteLabel_ {nullptr};
    QToolButton *bookmarkJumpButton_ {nullptr};
    QToolButton *sceneRefreshButton_ {nullptr};
    QToolButton *sceneExportButton_ {nullptr};
    QToolButton *sceneBookmarkButton_ {nullptr};
    QLineEdit *sceneSearchEdit_ {nullptr};
    QSpinBox *sceneStepSpinBox_ {nullptr};
    QLabel *sceneStatusLabel_ {nullptr};
    QListWidget *sceneList_ {nullptr};
    QComboBox *secondarySubtitleCombo_ {nullptr};
    QDoubleSpinBox *subtitleDelayCustomSpinBox_ {nullptr};
    QLineEdit *subtitleLanguageHintEdit_ {nullptr};
    QLabel *subtitleAutomationStatusLabel_ {nullptr};
    QCheckBox *subtitleRememberDelayForMediaCheckBox_ {nullptr};
    QCheckBox *audioNormalizeCheckBox_ {nullptr};
    QLineEdit *customAudioFilterEdit_ {nullptr};
    QLineEdit *customVideoFilterEdit_ {nullptr};
    QLineEdit *stereo3dFilterEdit_ {nullptr};
    QLineEdit *shaderPathEdit_ {nullptr};
    QLabel *mediaLabStatusLabel_ {nullptr};
    QSlider *videoBrightnessSlider_ {nullptr};
    QSlider *videoContrastSlider_ {nullptr};
    QSlider *videoSaturationSlider_ {nullptr};
    QSlider *videoGammaSlider_ {nullptr};
    QSlider *videoHueSlider_ {nullptr};
    QSlider *videoSharpenSlider_ {nullptr};
    QSlider *videoDenoiseSlider_ {nullptr};
    QCheckBox *videoDebandCheckBox_ {nullptr};
    QCheckBox *videoDeinterlaceCheckBox_ {nullptr};
    QListWidget *bookmarksList_ {nullptr};
    QListWidget *favoritesList_ {nullptr};
    QListWidget *chaptersList_ {nullptr};
    QTreeWidget *tracksTree_ {nullptr};
    QWidget *homeDashboard_ {nullptr};
    QLabel *homeDashboardTitleLabel_ {nullptr};
    QLabel *homeDashboardSubtitleLabel_ {nullptr};
    QGridLayout *homeDashboardGridLayout_ {nullptr};
    QListWidget *dashboardContinueList_ {nullptr};
    QListWidget *dashboardRecentList_ {nullptr};
    QListWidget *dashboardFavoritesList_ {nullptr};
    QListWidget *dashboardPinnedCoursesList_ {nullptr};
    QToolButton *dashboardOpenFileButton_ {nullptr};
    QToolButton *dashboardOpenUrlButton_ {nullptr};
    QVector<QSlider *> equalizerSliders_;
    QAction *openFileAction_ {nullptr};
    QAction *openFolderAction_ {nullptr};
    QAction *openUrlAction_ {nullptr};
    QAction *openCompareSourceAction_ {nullptr};
    QAction *loadSubtitleAction_ {nullptr};
    QAction *toggleSubtitleVisibilityAction_ {nullptr};
    QAction *subtitleScaleDownAction_ {nullptr};
    QAction *subtitleScaleUpAction_ {nullptr};
    QAction *subtitleScaleResetAction_ {nullptr};
    QAction *subtitlePositionUpAction_ {nullptr};
    QAction *subtitlePositionDownAction_ {nullptr};
    QAction *subtitlePositionResetAction_ {nullptr};
    QAction *cycleSubtitleAssOverrideAction_ {nullptr};
    QAction *showMediaInfoAction_ {nullptr};
    QAction *preferencesAction_ {nullptr};
    QAction *closeApplicationAction_ {nullptr};
    QAction *showScreenshotSuiteAction_ {nullptr};
    QAction *resetLayoutAction_ {nullptr};
    QAction *saveLayoutPresetAction_ {nullptr};
    QAction *loadLayoutPresetAction_ {nullptr};
    QAction *deleteLayoutPresetAction_ {nullptr};
    QAction *takeScreenshotAction_ {nullptr};
    QAction *favoriteCurrentMediaAction_ {nullptr};
    QAction *addBookmarkAction_ {nullptr};
    QAction *deleteBookmarkAction_ {nullptr};
    QAction *setLoopStartAction_ {nullptr};
    QAction *setLoopEndAction_ {nullptr};
    QAction *clearLoopAction_ {nullptr};
    QAction *frameStepBackwardAction_ {nullptr};
    QAction *frameStepForwardAction_ {nullptr};
    QAction *alwaysOnTopAction_ {nullptr};
    QMenu *profileMenu_ {nullptr};
    QActionGroup *profileActionGroup_ {nullptr};
    QActionGroup *repeatModeActionGroup_ {nullptr};
    QMenu *themeMenu_ {nullptr};
    QActionGroup *themeActionGroup_ {nullptr};
    QMenu *aspectMenu_ {nullptr};
    QActionGroup *aspectActionGroup_ {nullptr};
    QMenu *videoQualityMenu_ {nullptr};
    QActionGroup *videoQualityActionGroup_ {nullptr};
    QMenu *cropMenu_ {nullptr};
    QActionGroup *cropActionGroup_ {nullptr};
    QMenu *rotateMenu_ {nullptr};
    QActionGroup *rotateActionGroup_ {nullptr};
    QActionGroup *subtitleOverrideActionGroup_ {nullptr};
    QActionGroup *controlBarSubtitleTrackActionGroup_ {nullptr};
    QAction *playPauseAction_ {nullptr};
    QAction *stopAction_ {nullptr};
    QAction *seekBackwardShortAction_ {nullptr};
    QAction *seekForwardShortAction_ {nullptr};
    QAction *seekBackwardLongAction_ {nullptr};
    QAction *seekForwardLongAction_ {nullptr};
    QAction *volumeDownAction_ {nullptr};
    QAction *volumeUpAction_ {nullptr};
    QAction *toggleMuteAction_ {nullptr};
    QAction *videoZoomOutAction_ {nullptr};
    QAction *videoZoomInAction_ {nullptr};
    QAction *videoZoomResetAction_ {nullptr};
    QAction *videoPanLeftAction_ {nullptr};
    QAction *videoPanRightAction_ {nullptr};
    QAction *videoPanUpAction_ {nullptr};
    QAction *videoPanDownAction_ {nullptr};
    QAction *speedDownAction_ {nullptr};
    QAction *speedUpAction_ {nullptr};
    QAction *speedResetAction_ {nullptr};
    QAction *subtitleDelayDownAction_ {nullptr};
    QAction *subtitleDelayUpAction_ {nullptr};
    QAction *subtitleDelayResetAction_ {nullptr};
    QAction *subtitleDelayManualAction_ {nullptr};
    QAction *audioDelayDownAction_ {nullptr};
    QAction *audioDelayUpAction_ {nullptr};
    QAction *audioDelayResetAction_ {nullptr};
    QAction *audioDelayManualAction_ {nullptr};
    QAction *deinterlaceAction_ {nullptr};
    QAction *showMediaInformationOverlayAction_ {nullptr};
    QAction *aspectDefaultAction_ {nullptr};
    QAction *aspect16x9Action_ {nullptr};
    QAction *aspect4x3Action_ {nullptr};
    QAction *aspect185Action_ {nullptr};
    QAction *aspect235Action_ {nullptr};
    QAction *cropDefaultAction_ {nullptr};
    QAction *crop16x9Action_ {nullptr};
    QAction *crop185Action_ {nullptr};
    QAction *crop235Action_ {nullptr};
    QAction *cropDisableAction_ {nullptr};
    QAction *rotateDefaultAction_ {nullptr};
    QAction *rotate90Action_ {nullptr};
    QAction *rotate180Action_ {nullptr};
    QAction *rotate270Action_ {nullptr};
    QAction *subtitleOverrideScaleAction_ {nullptr};
    QAction *subtitleOverrideYesAction_ {nullptr};
    QAction *subtitleOverrideForceAction_ {nullptr};
    QAction *subtitleOverrideStripAction_ {nullptr};
    QAction *subtitleOverrideNoAction_ {nullptr};
    QAction *previousPlaylistAction_ {nullptr};
    QAction *nextPlaylistAction_ {nullptr};
    QAction *previousChapterAction_ {nullptr};
    QAction *nextChapterAction_ {nullptr};
    QAction *togglePlaylistAction_ {nullptr};
    QAction *toggleDetailsAction_ {nullptr};
    QAction *toggleFullscreenAction_ {nullptr};
    QAction *toggleCompareSideBySideAction_ {nullptr};
    QAction *toggleCompareABAction_ {nullptr};
    QAction *toggleCompareViewAction_ {nullptr};
    QAction *repeatOffAction_ {nullptr};
    QAction *repeatFileAction_ {nullptr};
    QAction *repeatPlaylistAction_ {nullptr};
    QByteArray defaultWindowState_;
    QString previewHoverSource_;
    QString currentMediaSource_;
    QString loadingMediaSource_;
    QString currentTitle_;
    QString currentRepeatMode_ {QStringLiteral("off")};
    QString activePlaylistViewPresetKey_;
    QString pinnedCourseBrowserFolderPath_;
    QString pinnedCourseBrowserRootPath_;
    QString activePlaylistThumbnailSource_;
    QString activePlaylistThumbnailRequestKey_;
    QString activePlaylistThumbnailOutputPath_;
    QString compareSource_;
    QString compareModeId_ {QStringLiteral("off")};
    QVector<revaplayer::domain::TrackInfo> currentTracks_;
    QVector<revaplayer::domain::Bookmark> currentBookmarks_;
    QVector<revaplayer::infrastructure::storage::PlaybackHistoryRecord> historyEntries_;
    QVector<revaplayer::domain::PlaylistEntry> playbackPlaylistEntriesCache_;
    QHash<QString, revaplayer::infrastructure::storage::PlaybackHistoryRecord> historyEntriesBySource_;
    QHash<QString, revaplayer::infrastructure::storage::ResumeStateRecord> resumeStateCache_;
    revaplayer::domain::PlaybackDiagnostics currentDiagnostics_;
    QHash<QString, revaplayer::services::media::MediaScanResult> mediaScanCache_;
    QSet<QString> mediaScanCacheLookupCompleted_;
    QSet<QString> progressResetSuppressedSources_;
    QHash<QString, QImage> playlistThumbnailCache_;
    QHash<QString, qint64> playlistThumbnailPendingBuckets_;
    QHash<QString, double> playlistThumbnailQueuedDurations_;
    QVector<qint64> bookmarkThumbnailQueue_;
    QVector<qint64> sceneThumbnailQueue_;
    QHash<qint64, QVector<int>> bookmarkRowsByBucket_;
    QHash<qint64, int> sceneRowByBucket_;
    QStringList playlistThumbnailQueue_;
    QPoint previewHoverAnchor_;
    double currentPositionSeconds_ {0.0};
    double currentDurationSeconds_ {0.0};
    double currentSpeed_ {1.0};
    double sessionPlaybackSpeed_ {1.0};
    double currentVideoZoomFactor_ {1.0};
    double currentVideoAlignX_ {0.0};
    double currentVideoAlignY_ {0.0};
    double currentSubtitleDelaySeconds_ {0.0};
    double currentSubtitleScale_ {1.0};
    double currentAudioDelaySeconds_ {0.0};
    double loopStartSeconds_ {-1.0};
    double loopEndSeconds_ {-1.0};
    double lastPersistedPositionSeconds_ {-1.0};
    double pendingCurrentMediaRestorePositionSeconds_ {-1.0};
    double previewHoverTimeSeconds_ {0.0};
    qint64 previewHoverBucketMilliseconds_ {-1};
    int playlistCount_ {0};
    int currentPlaylistIndex_ {-1};
    int pendingPlaylistSelectionIndex_ {-1};
    int pendingPlaylistSelectionExpectedCount_ {0};
    int pendingPlaylistSelectionRetryCount_ {0};
    QString pendingPlaylistSelectionSource_;
    QStringList pendingPlaylistReorderSelectedSources_;
    QString pendingPlaylistReorderCurrentSource_;
    QStringList pendingPlaylistRequestedOrderSources_;
    int pendingPlaylistViewportScrollValue_ {-1};
    int pendingPlaylistViewportHorizontalScrollValue_ {-1};
    bool preservePlaylistViewportAfterReorder_ {false};
    QHash<QString, QJsonObject> sessionVideoZoomStates_;
    QString pendingCurrentMediaRestoreSource_;
    QStringList pendingPlaylistNaturalOrderSources_;
    QStringList pinnedCourseBrowserHistory_;
    int chapterCount_ {0};
    int currentChapterIndex_ {-1};
    int currentVolume_ {100};
    int playbackPlaylistCurrentIndexCache_ {-1};
    int cachedPlaylistItemCount_ {0};
    int cachedPlaylistCompletedItemCount_ {0};
    int cachedPlaylistKnownDurationCount_ {0};
    int cachedPlaylistTotalProgress_ {0};
    bool muted_ {false};
    bool pinnedCourseBrowserActive_ {false};
    bool alwaysOnTop_ {false};
    bool mediaLoaded_ {false};
    bool loadingMedia_ {false};
    bool stopRequested_ {false};
    bool endOfFilePending_ {false};
    bool errorStateActive_ {false};
    int idleStateGeneration_ {0};
    bool resumeAttemptedForCurrentMedia_ {false};
    bool applyFullscreenOnShow_ {false};
    bool applyMaximizedOnShow_ {false};
    bool startupWindowModeApplied_ {false};
    bool hasVideoTrack_ {false};
    bool panelOverlayModeActive_ {false};
    bool suppressPanelPreferencePersistence_ {false};
    bool deinterlaceEnabled_ {false};
    bool playbackPaused_ {true};
    bool actionFeedbackOverlayEnabled_ {true};
    bool mediaInformationOverlayVisible_ {false};
    bool subtitleVisible_ {true};
    bool sceneBrowserLoading_ {false};
    bool localSubtitlesAutoLoadedForCurrentMedia_ {false};
    bool favoriteCurrentMedia_ {false};
    bool displaySleepInhibited_ {false};
    bool displaySleepXdgSuspended_ {false};
    bool playlistViewPresetApplyInProgress_ {false};
    bool applyingRememberedSubtitleTrackChoice_ {false};
    bool playlistActivationPanelRestorePending_ {false};
    bool playlistActivationPlaylistVisible_ {true};
    bool playlistActivationDetailsVisible_ {false};
    bool temporaryPlaylistHidePending_ {false};
    bool controlBarOverlayModeActive_ {false};
    bool overlayPanelResizeActive_ {false};
    bool pointerNearRightEdge_ {false};
    bool sidePanelEdgeRevealActive_ {false};
    bool playlistMetadataFullScanRequested_ {false};
    QString activeMouseZoneId_;
    struct MediaFileSystemMetadata {
        bool exists {false};
        bool isFile {false};
        bool hasSubtitleSibling {false};
        QString absoluteFilePath;
        QString dirPath;
        QString completeBaseName;
        QString suffix;
        qint64 size {-1};
        qint64 lastModifiedMs {-1};
    };

    QHash<QString, MediaFileSystemMetadata> mediaFileSystemCache_;
    QSet<QString> pendingMediaScanSources_;
    QSet<QString> failedMediaScanSources_;
    QHash<QString, int> mediaScanFailureCounts_;
    QHash<QString, QString> mediaScanFailureReasons_;
    QSet<QString> playlistThumbnailFailedRequestKeys_;
    QSet<QString> resumeStateLookupCompleted_;
    bool comparePrimaryVisible_ {true};
    bool compareSourceLoaded_ {false};
    bool firstRunPromptShown_ {false};
    bool fullscreenTransitionActive_ {false};
    bool pendingPlaylistMetadataRefresh_ {false};
    bool suppressVideoOverlayUpdates_ {false};
    bool preFullscreenMenuBarVisible_ {true};
    bool preFullscreenStatusBarVisible_ {true};
    bool preFullscreenControlBarVisible_ {true};
    bool preFullscreenPlaylistVisible_ {false};
    bool preFullscreenDetailsVisible_ {false};
    bool fullscreenChromeStateCaptured_ {false};
    int playlistActivationDetailsTabIndex_ {0};
    SidePanel playlistActivationSidePanel_ {SidePanel::Playlist};
    SidePanel activeSidePanel_ {SidePanel::Playlist};
    QString currentAspectOverride_ {QStringLiteral("no")};
    QString currentCropPreset_;
    QString currentSubtitleFontFamily_ {QStringLiteral("sans-serif")};
    QString currentSubtitleAssOverride_ {QStringLiteral("scale")};
    int currentVideoRotationDegrees_ {0};
    int currentSubtitlePosition_ {100};
    int currentSubtitleFontSize_ {38};
    int playlistOverlayPanelWidth_ {0};
    int detailsOverlayPanelWidth_ {0};
    int overlayPanelWidth_ {0};
    int overlayPanelResizeStartGlobalX_ {0};
    int overlayPanelResizeStartWidth_ {0};
    int pendingBurstScreenshots_ {0};
    int completedBurstScreenshots_ {0};
    int pendingBurstIntervalMs_ {0};
    int playlistMetadataScanBatchTotal_ {0};
    int playbackUiRefreshIntervalMs_ {350};
    int playlistPlaybackRefreshIntervalMs_ {1000};
    int progressSaveDeltaSeconds_ {12};
    int deferredStartupRefreshMs_ {1000};
    int playlistThumbnailInitialRows_ {8};
    int playlistThumbnailLookaheadRows_ {6};
    double cachedPlaylistTotalDurationSeconds_ {0.0};
    double cachedPlaylistWatchedDurationSeconds_ {0.0};
    QElapsedTimer playlistMetadataScanElapsed_;
    QElapsedTimer mediaInfoDialogRefreshElapsed_;
    QElapsedTimer playbackUiRefreshElapsed_;
    QElapsedTimer playlistPlaybackRefreshElapsed_;
    QElapsedTimer pointerPanelSuppressionElapsed_;
    int pointerPanelSuppressionDurationMs_ {0};
    QString sceneBrowserSource_;
    QString pendingBurstMediaLabel_;
    QString pendingBurstFormat_ {QStringLiteral("png")};
    uint displaySleepScreenSaverCookie_ {0};
    uint displaySleepGnomeSessionCookie_ {0};
    QTimer *burstScreenshotTimer_ {nullptr};
    QProcess *displaySleepInhibitorProcess_ {nullptr};
    QProcess *playlistThumbnailProcess_ {nullptr};
};

}  // namespace revaplayer::ui
